- name: Getting join command from the master node...
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Getting join command from the master node...
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"

- name: Print join command
  debug:
    var: join_command

- name: Copy join command to local file...
  become: yes
  local_action: copy content="{{ join_command }}" dest="/tmp/join_command" mode=0777