- name: Adding required containerd settings
  become: true
  blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
           net.bridge.bridge-nf-call-iptables = 1
           net.ipv4.ip_forward = 1
           net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply settings without restart
  become: true
  command: sysctl --system
